# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

#platform :ios, :deployment_target => '8.0'
target "ExampleProject2" do
    pod 'KINWebBrowser'
end

